//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC_05_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class warga
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public warga()
        {
            this.vaksinasis = new HashSet<vaksinasi>();
        }
    
        public string nik { get; set; }
        public string nama { get; set; }
        public string tempat_lahir { get; set; }
        public Nullable<System.DateTime> tanggal_lahir { get; set; }
        public string alamat { get; set; }
        public string noHp { get; set; }
        public Nullable<int> id_user { get; set; }
    
        public virtual admin admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vaksinasi> vaksinasis { get; set; }
    }
}
